// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rawdata/DropLimitScoreConf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace fat.rawdata {

  /// <summary>Holder for reflection information generated from rawdata/DropLimitScoreConf.proto</summary>
  public static partial class DropLimitScoreConfReflection {

    #region Descriptor
    /// <summary>File descriptor for rawdata/DropLimitScoreConf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DropLimitScoreConfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiByYXdkYXRhL0Ryb3BMaW1pdFNjb3JlQ29uZi5wcm90bxIHcmF3ZGF0YSL5",
            "AQoORHJvcExpbWl0U2NvcmUSCgoCaWQYASABKAUSOQoJaXRlbVNjb3JlGAIg",
            "AygLMiYucmF3ZGF0YS5Ecm9wTGltaXRTY29yZS5JdGVtU2NvcmVFbnRyeRI7",
            "CgpvcmRlclNjb3JlGAMgAygLMicucmF3ZGF0YS5Ecm9wTGltaXRTY29yZS5P",
            "cmRlclNjb3JlRW50cnkaMAoOSXRlbVNjb3JlRW50cnkSCwoDa2V5GAEgASgF",
            "Eg0KBXZhbHVlGAIgASgFOgI4ARoxCg9PcmRlclNjb3JlRW50cnkSCwoDa2V5",
            "GAEgASgFEg0KBXZhbHVlGAIgASgFOgI4ASLCAQoYRHJvcExpbWl0U2NvcmVN",
            "YXBBQlZhbHVlElMKEURyb3BMaW1pdFNjb3JlTWFwGAEgAygLMjgucmF3ZGF0",
            "YS5Ecm9wTGltaXRTY29yZU1hcEFCVmFsdWUuRHJvcExpbWl0U2NvcmVNYXBF",
            "bnRyeRpRChZEcm9wTGltaXRTY29yZU1hcEVudHJ5EgsKA2tleRgBIAEoBRIm",
            "CgV2YWx1ZRgCIAEoCzIXLnJhd2RhdGEuRHJvcExpbWl0U2NvcmU6AjgBIqkE",
            "ChJEcm9wTGltaXRTY29yZUNvbmYSTQoRRHJvcExpbWl0U2NvcmVNYXAYASAD",
            "KAsyMi5yYXdkYXRhLkRyb3BMaW1pdFNjb3JlQ29uZi5Ecm9wTGltaXRTY29y",
            "ZU1hcEVudHJ5ElEKE0Ryb3BMaW1pdFNjb3JlTWFwQUIYAiADKAsyNC5yYXdk",
            "YXRhLkRyb3BMaW1pdFNjb3JlQ29uZi5Ecm9wTGltaXRTY29yZU1hcEFCRW50",
            "cnkSWwoYRHJvcExpbWl0U2NvcmVNYXBBQlBhdGNoGAMgAygLMjkucmF3ZGF0",
            "YS5Ecm9wTGltaXRTY29yZUNvbmYuRHJvcExpbWl0U2NvcmVNYXBBQlBhdGNo",
            "RW50cnkaUQoWRHJvcExpbWl0U2NvcmVNYXBFbnRyeRILCgNrZXkYASABKAUS",
            "JgoFdmFsdWUYAiABKAsyFy5yYXdkYXRhLkRyb3BMaW1pdFNjb3JlOgI4ARpd",
            "ChhEcm9wTGltaXRTY29yZU1hcEFCRW50cnkSCwoDa2V5GAEgASgJEjAKBXZh",
            "bHVlGAIgASgLMiEucmF3ZGF0YS5Ecm9wTGltaXRTY29yZU1hcEFCVmFsdWU6",
            "AjgBGmIKHURyb3BMaW1pdFNjb3JlTWFwQUJQYXRjaEVudHJ5EgsKA2tleRgB",
            "IAEoCRIwCgV2YWx1ZRgCIAEoCzIhLnJhd2RhdGEuRHJvcExpbWl0U2NvcmVN",
            "YXBBQlZhbHVlOgI4AUI9Wi1naXRsYWIuZnVucGx1cy5pby9mYXQvY29uZi9n",
            "ZW4vZ29sYW5nL3Jhd2RhdGGqAgtmYXQucmF3ZGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.DropLimitScore), global::fat.rawdata.DropLimitScore.Parser, new[]{ "Id", "ItemScore", "OrderScore" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.DropLimitScoreMapABValue), global::fat.rawdata.DropLimitScoreMapABValue.Parser, new[]{ "DropLimitScoreMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.DropLimitScoreConf), global::fat.rawdata.DropLimitScoreConf.Parser, new[]{ "DropLimitScoreMap", "DropLimitScoreMapAB", "DropLimitScoreMapABPatch" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// annotation@annotation_type(type="rawdata")
  /// annotation@rawdata(row="DropLimitScore",table="DropLimitScoreMap",table_wrapper="DropLimitScoreConf",map="true",map_key_type="int32",data="DropLimitScoreConf")
  /// annotation@ab(table_ab="DropLimitScoreMapAB",table_ab_patch="DropLimitScoreMapABPatch",table_ab_value="DropLimitScoreMapABValue",ab_patch="false")
  /// annotation@filter(just_server="false",just_client="false")
  /// annotation@DropLimitScore(id="id")
  /// </summary>
  public sealed partial class DropLimitScore : pb::IMessage<DropLimitScore>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DropLimitScore> _parser = new pb::MessageParser<DropLimitScore>(() => new DropLimitScore());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DropLimitScore> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.DropLimitScoreConfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScore() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScore(DropLimitScore other) : this() {
      id_ = other.id_;
      itemScore_ = other.itemScore_.Clone();
      orderScore_ = other.orderScore_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScore Clone() {
      return new DropLimitScore(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 分数计算规则ID
    /// annotation@field_id(id="true")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "itemScore" field.</summary>
    public const int ItemScoreFieldNumber = 2;
    private static readonly pbc::MapField<int, int>.Codec _map_itemScore_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 18);
    private readonly pbc::MapField<int, int> itemScore_ = new pbc::MapField<int, int>();
    /// <summary>
    /// 限制分数
    /// （ObjBasic.id : scoreNum）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> ItemScore {
      get { return itemScore_; }
    }

    /// <summary>Field number for the "orderScore" field.</summary>
    public const int OrderScoreFieldNumber = 3;
    private static readonly pbc::MapField<int, int>.Codec _map_orderScore_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 26);
    private readonly pbc::MapField<int, int> orderScore_ = new pbc::MapField<int, int>();
    /// <summary>
    /// 分数计算信息
    /// （OrderCommon.id : scoreNum）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> OrderScore {
      get { return orderScore_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DropLimitScore);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DropLimitScore other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!ItemScore.Equals(other.ItemScore)) return false;
      if (!OrderScore.Equals(other.OrderScore)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= ItemScore.GetHashCode();
      hash ^= OrderScore.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      itemScore_.WriteTo(output, _map_itemScore_codec);
      orderScore_.WriteTo(output, _map_orderScore_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      itemScore_.WriteTo(ref output, _map_itemScore_codec);
      orderScore_.WriteTo(ref output, _map_orderScore_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      size += itemScore_.CalculateSize(_map_itemScore_codec);
      size += orderScore_.CalculateSize(_map_orderScore_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DropLimitScore other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      itemScore_.Add(other.itemScore_);
      orderScore_.Add(other.orderScore_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            itemScore_.AddEntriesFrom(input, _map_itemScore_codec);
            break;
          }
          case 26: {
            orderScore_.AddEntriesFrom(input, _map_orderScore_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            itemScore_.AddEntriesFrom(ref input, _map_itemScore_codec);
            break;
          }
          case 26: {
            orderScore_.AddEntriesFrom(ref input, _map_orderScore_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DropLimitScoreMapABValue : pb::IMessage<DropLimitScoreMapABValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DropLimitScoreMapABValue> _parser = new pb::MessageParser<DropLimitScoreMapABValue>(() => new DropLimitScoreMapABValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DropLimitScoreMapABValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.DropLimitScoreConfReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScoreMapABValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScoreMapABValue(DropLimitScoreMapABValue other) : this() {
      dropLimitScoreMap_ = other.dropLimitScoreMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScoreMapABValue Clone() {
      return new DropLimitScoreMapABValue(this);
    }

    /// <summary>Field number for the "DropLimitScoreMap" field.</summary>
    public const int DropLimitScoreMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.DropLimitScore>.Codec _map_dropLimitScoreMap_codec
        = new pbc::MapField<int, global::fat.rawdata.DropLimitScore>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.DropLimitScore.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.DropLimitScore> dropLimitScoreMap_ = new pbc::MapField<int, global::fat.rawdata.DropLimitScore>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.DropLimitScore> DropLimitScoreMap {
      get { return dropLimitScoreMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DropLimitScoreMapABValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DropLimitScoreMapABValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!DropLimitScoreMap.Equals(other.DropLimitScoreMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= DropLimitScoreMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dropLimitScoreMap_.WriteTo(output, _map_dropLimitScoreMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dropLimitScoreMap_.WriteTo(ref output, _map_dropLimitScoreMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dropLimitScoreMap_.CalculateSize(_map_dropLimitScoreMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DropLimitScoreMapABValue other) {
      if (other == null) {
        return;
      }
      dropLimitScoreMap_.Add(other.dropLimitScoreMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dropLimitScoreMap_.AddEntriesFrom(input, _map_dropLimitScoreMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dropLimitScoreMap_.AddEntriesFrom(ref input, _map_dropLimitScoreMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DropLimitScoreConf : pb::IMessage<DropLimitScoreConf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DropLimitScoreConf> _parser = new pb::MessageParser<DropLimitScoreConf>(() => new DropLimitScoreConf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DropLimitScoreConf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.DropLimitScoreConfReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScoreConf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScoreConf(DropLimitScoreConf other) : this() {
      dropLimitScoreMap_ = other.dropLimitScoreMap_.Clone();
      dropLimitScoreMapAB_ = other.dropLimitScoreMapAB_.Clone();
      dropLimitScoreMapABPatch_ = other.dropLimitScoreMapABPatch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DropLimitScoreConf Clone() {
      return new DropLimitScoreConf(this);
    }

    /// <summary>Field number for the "DropLimitScoreMap" field.</summary>
    public const int DropLimitScoreMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.DropLimitScore>.Codec _map_dropLimitScoreMap_codec
        = new pbc::MapField<int, global::fat.rawdata.DropLimitScore>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.DropLimitScore.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.DropLimitScore> dropLimitScoreMap_ = new pbc::MapField<int, global::fat.rawdata.DropLimitScore>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.DropLimitScore> DropLimitScoreMap {
      get { return dropLimitScoreMap_; }
    }

    /// <summary>Field number for the "DropLimitScoreMapAB" field.</summary>
    public const int DropLimitScoreMapABFieldNumber = 2;
    private static readonly pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue>.Codec _map_dropLimitScoreMapAB_codec
        = new pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.DropLimitScoreMapABValue.Parser), 18);
    private readonly pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue> dropLimitScoreMapAB_ = new pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue> DropLimitScoreMapAB {
      get { return dropLimitScoreMapAB_; }
    }

    /// <summary>Field number for the "DropLimitScoreMapABPatch" field.</summary>
    public const int DropLimitScoreMapABPatchFieldNumber = 3;
    private static readonly pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue>.Codec _map_dropLimitScoreMapABPatch_codec
        = new pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.DropLimitScoreMapABValue.Parser), 26);
    private readonly pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue> dropLimitScoreMapABPatch_ = new pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.DropLimitScoreMapABValue> DropLimitScoreMapABPatch {
      get { return dropLimitScoreMapABPatch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DropLimitScoreConf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DropLimitScoreConf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!DropLimitScoreMap.Equals(other.DropLimitScoreMap)) return false;
      if (!DropLimitScoreMapAB.Equals(other.DropLimitScoreMapAB)) return false;
      if (!DropLimitScoreMapABPatch.Equals(other.DropLimitScoreMapABPatch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= DropLimitScoreMap.GetHashCode();
      hash ^= DropLimitScoreMapAB.GetHashCode();
      hash ^= DropLimitScoreMapABPatch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dropLimitScoreMap_.WriteTo(output, _map_dropLimitScoreMap_codec);
      dropLimitScoreMapAB_.WriteTo(output, _map_dropLimitScoreMapAB_codec);
      dropLimitScoreMapABPatch_.WriteTo(output, _map_dropLimitScoreMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dropLimitScoreMap_.WriteTo(ref output, _map_dropLimitScoreMap_codec);
      dropLimitScoreMapAB_.WriteTo(ref output, _map_dropLimitScoreMapAB_codec);
      dropLimitScoreMapABPatch_.WriteTo(ref output, _map_dropLimitScoreMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dropLimitScoreMap_.CalculateSize(_map_dropLimitScoreMap_codec);
      size += dropLimitScoreMapAB_.CalculateSize(_map_dropLimitScoreMapAB_codec);
      size += dropLimitScoreMapABPatch_.CalculateSize(_map_dropLimitScoreMapABPatch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DropLimitScoreConf other) {
      if (other == null) {
        return;
      }
      dropLimitScoreMap_.Add(other.dropLimitScoreMap_);
      dropLimitScoreMapAB_.Add(other.dropLimitScoreMapAB_);
      dropLimitScoreMapABPatch_.Add(other.dropLimitScoreMapABPatch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dropLimitScoreMap_.AddEntriesFrom(input, _map_dropLimitScoreMap_codec);
            break;
          }
          case 18: {
            dropLimitScoreMapAB_.AddEntriesFrom(input, _map_dropLimitScoreMapAB_codec);
            break;
          }
          case 26: {
            dropLimitScoreMapABPatch_.AddEntriesFrom(input, _map_dropLimitScoreMapABPatch_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dropLimitScoreMap_.AddEntriesFrom(ref input, _map_dropLimitScoreMap_codec);
            break;
          }
          case 18: {
            dropLimitScoreMapAB_.AddEntriesFrom(ref input, _map_dropLimitScoreMapAB_codec);
            break;
          }
          case 26: {
            dropLimitScoreMapABPatch_.AddEntriesFrom(ref input, _map_dropLimitScoreMapABPatch_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
