// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rawdata/EventOrderStreakDetailConf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace fat.rawdata {

  /// <summary>Holder for reflection information generated from rawdata/EventOrderStreakDetailConf.proto</summary>
  public static partial class EventOrderStreakDetailConfReflection {

    #region Descriptor
    /// <summary>File descriptor for rawdata/EventOrderStreakDetailConf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventOrderStreakDetailConfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihyYXdkYXRhL0V2ZW50T3JkZXJTdHJlYWtEZXRhaWxDb25mLnByb3RvEgdy",
            "YXdkYXRhImYKFkV2ZW50T3JkZXJTdHJlYWtEZXRhaWwSCgoCaWQYASABKAUS",
            "DwoHYWN0U2xvdBgCIAEoBRIMCgRkaWZmGAUgASgFEhEKCW9yZGVyTGlzdBgD",
            "IAMoBRIOCgZyZXdhcmQYBCADKAki8gEKIEV2ZW50T3JkZXJTdHJlYWtEZXRh",
            "aWxNYXBBQlZhbHVlEmsKGUV2ZW50T3JkZXJTdHJlYWtEZXRhaWxNYXAYASAD",
            "KAsySC5yYXdkYXRhLkV2ZW50T3JkZXJTdHJlYWtEZXRhaWxNYXBBQlZhbHVl",
            "LkV2ZW50T3JkZXJTdHJlYWtEZXRhaWxNYXBFbnRyeRphCh5FdmVudE9yZGVy",
            "U3RyZWFrRGV0YWlsTWFwRW50cnkSCwoDa2V5GAEgASgFEi4KBXZhbHVlGAIg",
            "ASgLMh8ucmF3ZGF0YS5FdmVudE9yZGVyU3RyZWFrRGV0YWlsOgI4ASKpBQoa",
            "RXZlbnRPcmRlclN0cmVha0RldGFpbENvbmYSZQoZRXZlbnRPcmRlclN0cmVh",
            "a0RldGFpbE1hcBgBIAMoCzJCLnJhd2RhdGEuRXZlbnRPcmRlclN0cmVha0Rl",
            "dGFpbENvbmYuRXZlbnRPcmRlclN0cmVha0RldGFpbE1hcEVudHJ5EmkKG0V2",
            "ZW50T3JkZXJTdHJlYWtEZXRhaWxNYXBBQhgCIAMoCzJELnJhd2RhdGEuRXZl",
            "bnRPcmRlclN0cmVha0RldGFpbENvbmYuRXZlbnRPcmRlclN0cmVha0RldGFp",
            "bE1hcEFCRW50cnkScwogRXZlbnRPcmRlclN0cmVha0RldGFpbE1hcEFCUGF0",
            "Y2gYAyADKAsySS5yYXdkYXRhLkV2ZW50T3JkZXJTdHJlYWtEZXRhaWxDb25m",
            "LkV2ZW50T3JkZXJTdHJlYWtEZXRhaWxNYXBBQlBhdGNoRW50cnkaYQoeRXZl",
            "bnRPcmRlclN0cmVha0RldGFpbE1hcEVudHJ5EgsKA2tleRgBIAEoBRIuCgV2",
            "YWx1ZRgCIAEoCzIfLnJhd2RhdGEuRXZlbnRPcmRlclN0cmVha0RldGFpbDoC",
            "OAEabQogRXZlbnRPcmRlclN0cmVha0RldGFpbE1hcEFCRW50cnkSCwoDa2V5",
            "GAEgASgJEjgKBXZhbHVlGAIgASgLMikucmF3ZGF0YS5FdmVudE9yZGVyU3Ry",
            "ZWFrRGV0YWlsTWFwQUJWYWx1ZToCOAEacgolRXZlbnRPcmRlclN0cmVha0Rl",
            "dGFpbE1hcEFCUGF0Y2hFbnRyeRILCgNrZXkYASABKAkSOAoFdmFsdWUYAiAB",
            "KAsyKS5yYXdkYXRhLkV2ZW50T3JkZXJTdHJlYWtEZXRhaWxNYXBBQlZhbHVl",
            "OgI4AUI9Wi1naXRsYWIuZnVucGx1cy5pby9mYXQvY29uZi9nZW4vZ29sYW5n",
            "L3Jhd2RhdGGqAgtmYXQucmF3ZGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.EventOrderStreakDetail), global::fat.rawdata.EventOrderStreakDetail.Parser, new[]{ "Id", "ActSlot", "Diff", "OrderList", "Reward" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.EventOrderStreakDetailMapABValue), global::fat.rawdata.EventOrderStreakDetailMapABValue.Parser, new[]{ "EventOrderStreakDetailMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.EventOrderStreakDetailConf), global::fat.rawdata.EventOrderStreakDetailConf.Parser, new[]{ "EventOrderStreakDetailMap", "EventOrderStreakDetailMapAB", "EventOrderStreakDetailMapABPatch" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// annotation@annotation_type(type="rawdata")
  /// annotation@rawdata(row="EventOrderStreakDetail",table="EventOrderStreakDetailMap",table_wrapper="EventOrderStreakDetailConf",map="true",map_key_type="int32",data="EventOrderStreakDetailConf")
  /// annotation@ab(table_ab="EventOrderStreakDetailMapAB",table_ab_patch="EventOrderStreakDetailMapABPatch",table_ab_value="EventOrderStreakDetailMapABValue",ab_patch="false")
  /// annotation@filter(just_server="false",just_client="false")
  /// annotation@EventOrderStreakDetail(id="id")
  /// </summary>
  public sealed partial class EventOrderStreakDetail : pb::IMessage<EventOrderStreakDetail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventOrderStreakDetail> _parser = new pb::MessageParser<EventOrderStreakDetail>(() => new EventOrderStreakDetail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventOrderStreakDetail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.EventOrderStreakDetailConfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetail(EventOrderStreakDetail other) : this() {
      id_ = other.id_;
      actSlot_ = other.actSlot_;
      diff_ = other.diff_;
      orderList_ = other.orderList_.Clone();
      reward_ = other.reward_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetail Clone() {
      return new EventOrderStreakDetail(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 活动详情id
    /// annotation@field_id(id="true")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "actSlot" field.</summary>
    public const int ActSlotFieldNumber = 2;
    private int actSlot_;
    /// <summary>
    /// 用来承载活动订单的槽位
    /// （OrderRandomer.id）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActSlot {
      get { return actSlot_; }
      set {
        actSlot_ = value;
      }
    }

    /// <summary>Field number for the "diff" field.</summary>
    public const int DiffFieldNumber = 5;
    private int diff_;
    /// <summary>
    /// 仅用作TGA；活动难度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Diff {
      get { return diff_; }
      set {
        diff_ = value;
      }
    }

    /// <summary>Field number for the "orderList" field.</summary>
    public const int OrderListFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_orderList_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> orderList_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 订单序列
    /// （OrderRandomer.id）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> OrderList {
      get { return orderList_; }
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_reward_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> reward_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// 活动最终奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Reward {
      get { return reward_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventOrderStreakDetail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventOrderStreakDetail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ActSlot != other.ActSlot) return false;
      if (Diff != other.Diff) return false;
      if(!orderList_.Equals(other.orderList_)) return false;
      if(!reward_.Equals(other.reward_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (ActSlot != 0) hash ^= ActSlot.GetHashCode();
      if (Diff != 0) hash ^= Diff.GetHashCode();
      hash ^= orderList_.GetHashCode();
      hash ^= reward_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ActSlot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActSlot);
      }
      orderList_.WriteTo(output, _repeated_orderList_codec);
      reward_.WriteTo(output, _repeated_reward_codec);
      if (Diff != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Diff);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ActSlot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActSlot);
      }
      orderList_.WriteTo(ref output, _repeated_orderList_codec);
      reward_.WriteTo(ref output, _repeated_reward_codec);
      if (Diff != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Diff);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (ActSlot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActSlot);
      }
      if (Diff != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diff);
      }
      size += orderList_.CalculateSize(_repeated_orderList_codec);
      size += reward_.CalculateSize(_repeated_reward_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventOrderStreakDetail other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.ActSlot != 0) {
        ActSlot = other.ActSlot;
      }
      if (other.Diff != 0) {
        Diff = other.Diff;
      }
      orderList_.Add(other.orderList_);
      reward_.Add(other.reward_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            ActSlot = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            orderList_.AddEntriesFrom(input, _repeated_orderList_codec);
            break;
          }
          case 34: {
            reward_.AddEntriesFrom(input, _repeated_reward_codec);
            break;
          }
          case 40: {
            Diff = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            ActSlot = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            orderList_.AddEntriesFrom(ref input, _repeated_orderList_codec);
            break;
          }
          case 34: {
            reward_.AddEntriesFrom(ref input, _repeated_reward_codec);
            break;
          }
          case 40: {
            Diff = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EventOrderStreakDetailMapABValue : pb::IMessage<EventOrderStreakDetailMapABValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventOrderStreakDetailMapABValue> _parser = new pb::MessageParser<EventOrderStreakDetailMapABValue>(() => new EventOrderStreakDetailMapABValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventOrderStreakDetailMapABValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.EventOrderStreakDetailConfReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetailMapABValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetailMapABValue(EventOrderStreakDetailMapABValue other) : this() {
      eventOrderStreakDetailMap_ = other.eventOrderStreakDetailMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetailMapABValue Clone() {
      return new EventOrderStreakDetailMapABValue(this);
    }

    /// <summary>Field number for the "EventOrderStreakDetailMap" field.</summary>
    public const int EventOrderStreakDetailMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail>.Codec _map_eventOrderStreakDetailMap_codec
        = new pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.EventOrderStreakDetail.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail> eventOrderStreakDetailMap_ = new pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail> EventOrderStreakDetailMap {
      get { return eventOrderStreakDetailMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventOrderStreakDetailMapABValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventOrderStreakDetailMapABValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!EventOrderStreakDetailMap.Equals(other.EventOrderStreakDetailMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= EventOrderStreakDetailMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      eventOrderStreakDetailMap_.WriteTo(output, _map_eventOrderStreakDetailMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      eventOrderStreakDetailMap_.WriteTo(ref output, _map_eventOrderStreakDetailMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += eventOrderStreakDetailMap_.CalculateSize(_map_eventOrderStreakDetailMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventOrderStreakDetailMapABValue other) {
      if (other == null) {
        return;
      }
      eventOrderStreakDetailMap_.Add(other.eventOrderStreakDetailMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            eventOrderStreakDetailMap_.AddEntriesFrom(input, _map_eventOrderStreakDetailMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            eventOrderStreakDetailMap_.AddEntriesFrom(ref input, _map_eventOrderStreakDetailMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EventOrderStreakDetailConf : pb::IMessage<EventOrderStreakDetailConf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventOrderStreakDetailConf> _parser = new pb::MessageParser<EventOrderStreakDetailConf>(() => new EventOrderStreakDetailConf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventOrderStreakDetailConf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.EventOrderStreakDetailConfReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetailConf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetailConf(EventOrderStreakDetailConf other) : this() {
      eventOrderStreakDetailMap_ = other.eventOrderStreakDetailMap_.Clone();
      eventOrderStreakDetailMapAB_ = other.eventOrderStreakDetailMapAB_.Clone();
      eventOrderStreakDetailMapABPatch_ = other.eventOrderStreakDetailMapABPatch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventOrderStreakDetailConf Clone() {
      return new EventOrderStreakDetailConf(this);
    }

    /// <summary>Field number for the "EventOrderStreakDetailMap" field.</summary>
    public const int EventOrderStreakDetailMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail>.Codec _map_eventOrderStreakDetailMap_codec
        = new pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.EventOrderStreakDetail.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail> eventOrderStreakDetailMap_ = new pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.EventOrderStreakDetail> EventOrderStreakDetailMap {
      get { return eventOrderStreakDetailMap_; }
    }

    /// <summary>Field number for the "EventOrderStreakDetailMapAB" field.</summary>
    public const int EventOrderStreakDetailMapABFieldNumber = 2;
    private static readonly pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue>.Codec _map_eventOrderStreakDetailMapAB_codec
        = new pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.EventOrderStreakDetailMapABValue.Parser), 18);
    private readonly pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue> eventOrderStreakDetailMapAB_ = new pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue> EventOrderStreakDetailMapAB {
      get { return eventOrderStreakDetailMapAB_; }
    }

    /// <summary>Field number for the "EventOrderStreakDetailMapABPatch" field.</summary>
    public const int EventOrderStreakDetailMapABPatchFieldNumber = 3;
    private static readonly pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue>.Codec _map_eventOrderStreakDetailMapABPatch_codec
        = new pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.EventOrderStreakDetailMapABValue.Parser), 26);
    private readonly pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue> eventOrderStreakDetailMapABPatch_ = new pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.EventOrderStreakDetailMapABValue> EventOrderStreakDetailMapABPatch {
      get { return eventOrderStreakDetailMapABPatch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventOrderStreakDetailConf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventOrderStreakDetailConf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!EventOrderStreakDetailMap.Equals(other.EventOrderStreakDetailMap)) return false;
      if (!EventOrderStreakDetailMapAB.Equals(other.EventOrderStreakDetailMapAB)) return false;
      if (!EventOrderStreakDetailMapABPatch.Equals(other.EventOrderStreakDetailMapABPatch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= EventOrderStreakDetailMap.GetHashCode();
      hash ^= EventOrderStreakDetailMapAB.GetHashCode();
      hash ^= EventOrderStreakDetailMapABPatch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      eventOrderStreakDetailMap_.WriteTo(output, _map_eventOrderStreakDetailMap_codec);
      eventOrderStreakDetailMapAB_.WriteTo(output, _map_eventOrderStreakDetailMapAB_codec);
      eventOrderStreakDetailMapABPatch_.WriteTo(output, _map_eventOrderStreakDetailMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      eventOrderStreakDetailMap_.WriteTo(ref output, _map_eventOrderStreakDetailMap_codec);
      eventOrderStreakDetailMapAB_.WriteTo(ref output, _map_eventOrderStreakDetailMapAB_codec);
      eventOrderStreakDetailMapABPatch_.WriteTo(ref output, _map_eventOrderStreakDetailMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += eventOrderStreakDetailMap_.CalculateSize(_map_eventOrderStreakDetailMap_codec);
      size += eventOrderStreakDetailMapAB_.CalculateSize(_map_eventOrderStreakDetailMapAB_codec);
      size += eventOrderStreakDetailMapABPatch_.CalculateSize(_map_eventOrderStreakDetailMapABPatch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventOrderStreakDetailConf other) {
      if (other == null) {
        return;
      }
      eventOrderStreakDetailMap_.Add(other.eventOrderStreakDetailMap_);
      eventOrderStreakDetailMapAB_.Add(other.eventOrderStreakDetailMapAB_);
      eventOrderStreakDetailMapABPatch_.Add(other.eventOrderStreakDetailMapABPatch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            eventOrderStreakDetailMap_.AddEntriesFrom(input, _map_eventOrderStreakDetailMap_codec);
            break;
          }
          case 18: {
            eventOrderStreakDetailMapAB_.AddEntriesFrom(input, _map_eventOrderStreakDetailMapAB_codec);
            break;
          }
          case 26: {
            eventOrderStreakDetailMapABPatch_.AddEntriesFrom(input, _map_eventOrderStreakDetailMapABPatch_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            eventOrderStreakDetailMap_.AddEntriesFrom(ref input, _map_eventOrderStreakDetailMap_codec);
            break;
          }
          case 18: {
            eventOrderStreakDetailMapAB_.AddEntriesFrom(ref input, _map_eventOrderStreakDetailMapAB_codec);
            break;
          }
          case 26: {
            eventOrderStreakDetailMapABPatch_.AddEntriesFrom(ref input, _map_eventOrderStreakDetailMapABPatch_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
