// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rawdata/LangTrHotfixConf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace fat.rawdata {

  /// <summary>Holder for reflection information generated from rawdata/LangTrHotfixConf.proto</summary>
  public static partial class LangTrHotfixConfReflection {

    #region Descriptor
    /// <summary>File descriptor for rawdata/LangTrHotfixConf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LangTrHotfixConfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5yYXdkYXRhL0xhbmdUckhvdGZpeENvbmYucHJvdG8SB3Jhd2RhdGEiKAoM",
            "TGFuZ1RySG90Zml4EgoKAkxLGAEgASgJEgwKBE5hbWUYAiABKAkiTAoYTGFu",
            "Z1RySG90Zml4U2xpY2VBQlZhbHVlEjAKEUxhbmdUckhvdGZpeFNsaWNlGAEg",
            "AygLMhUucmF3ZGF0YS5MYW5nVHJIb3RmaXgiswMKEExhbmdUckhvdGZpeENv",
            "bmYSMAoRTGFuZ1RySG90Zml4U2xpY2UYASADKAsyFS5yYXdkYXRhLkxhbmdU",
            "ckhvdGZpeBJPChNMYW5nVHJIb3RmaXhTbGljZUFCGAIgAygLMjIucmF3ZGF0",
            "YS5MYW5nVHJIb3RmaXhDb25mLkxhbmdUckhvdGZpeFNsaWNlQUJFbnRyeRJZ",
            "ChhMYW5nVHJIb3RmaXhTbGljZUFCUGF0Y2gYAyADKAsyNy5yYXdkYXRhLkxh",
            "bmdUckhvdGZpeENvbmYuTGFuZ1RySG90Zml4U2xpY2VBQlBhdGNoRW50cnka",
            "XQoYTGFuZ1RySG90Zml4U2xpY2VBQkVudHJ5EgsKA2tleRgBIAEoCRIwCgV2",
            "YWx1ZRgCIAEoCzIhLnJhd2RhdGEuTGFuZ1RySG90Zml4U2xpY2VBQlZhbHVl",
            "OgI4ARpiCh1MYW5nVHJIb3RmaXhTbGljZUFCUGF0Y2hFbnRyeRILCgNrZXkY",
            "ASABKAkSMAoFdmFsdWUYAiABKAsyIS5yYXdkYXRhLkxhbmdUckhvdGZpeFNs",
            "aWNlQUJWYWx1ZToCOAFCPVotZ2l0bGFiLmZ1bnBsdXMuaW8vZmF0L2NvbmYv",
            "Z2VuL2dvbGFuZy9yYXdkYXRhqgILZmF0LnJhd2RhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.LangTrHotfix), global::fat.rawdata.LangTrHotfix.Parser, new[]{ "LK", "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.LangTrHotfixSliceABValue), global::fat.rawdata.LangTrHotfixSliceABValue.Parser, new[]{ "LangTrHotfixSlice" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.LangTrHotfixConf), global::fat.rawdata.LangTrHotfixConf.Parser, new[]{ "LangTrHotfixSlice", "LangTrHotfixSliceAB", "LangTrHotfixSliceABPatch" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// annotation@annotation_type(type="rawdata")
  /// annotation@rawdata(row="LangTrHotfix",table="LangTrHotfixSlice",table_wrapper="LangTrHotfixConf",map="false",map_key_type="",data="LangTrHotfixConf")
  /// annotation@ab(table_ab="LangTrHotfixSliceAB",table_ab_patch="LangTrHotfixSliceABPatch",table_ab_value="LangTrHotfixSliceABValue",ab_patch="false")
  /// annotation@filter(just_server="false",just_client="false")
  /// </summary>
  public sealed partial class LangTrHotfix : pb::IMessage<LangTrHotfix>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LangTrHotfix> _parser = new pb::MessageParser<LangTrHotfix>(() => new LangTrHotfix());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LangTrHotfix> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.LangTrHotfixConfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfix() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfix(LangTrHotfix other) : this() {
      lK_ = other.lK_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfix Clone() {
      return new LangTrHotfix(this);
    }

    /// <summary>Field number for the "LK" field.</summary>
    public const int LKFieldNumber = 1;
    private string lK_ = "";
    /// <summary>
    /// key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LK {
      get { return lK_; }
      set {
        lK_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    /// 土耳其语
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LangTrHotfix);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LangTrHotfix other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LK != other.LK) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LK.Length != 0) hash ^= LK.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LK.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LK);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LK.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LK);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LK.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LK);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LangTrHotfix other) {
      if (other == null) {
        return;
      }
      if (other.LK.Length != 0) {
        LK = other.LK;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LK = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LK = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LangTrHotfixSliceABValue : pb::IMessage<LangTrHotfixSliceABValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LangTrHotfixSliceABValue> _parser = new pb::MessageParser<LangTrHotfixSliceABValue>(() => new LangTrHotfixSliceABValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LangTrHotfixSliceABValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.LangTrHotfixConfReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfixSliceABValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfixSliceABValue(LangTrHotfixSliceABValue other) : this() {
      langTrHotfixSlice_ = other.langTrHotfixSlice_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfixSliceABValue Clone() {
      return new LangTrHotfixSliceABValue(this);
    }

    /// <summary>Field number for the "LangTrHotfixSlice" field.</summary>
    public const int LangTrHotfixSliceFieldNumber = 1;
    private static readonly pb::FieldCodec<global::fat.rawdata.LangTrHotfix> _repeated_langTrHotfixSlice_codec
        = pb::FieldCodec.ForMessage(10, global::fat.rawdata.LangTrHotfix.Parser);
    private readonly pbc::RepeatedField<global::fat.rawdata.LangTrHotfix> langTrHotfixSlice_ = new pbc::RepeatedField<global::fat.rawdata.LangTrHotfix>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::fat.rawdata.LangTrHotfix> LangTrHotfixSlice {
      get { return langTrHotfixSlice_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LangTrHotfixSliceABValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LangTrHotfixSliceABValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!langTrHotfixSlice_.Equals(other.langTrHotfixSlice_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= langTrHotfixSlice_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      langTrHotfixSlice_.WriteTo(output, _repeated_langTrHotfixSlice_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      langTrHotfixSlice_.WriteTo(ref output, _repeated_langTrHotfixSlice_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += langTrHotfixSlice_.CalculateSize(_repeated_langTrHotfixSlice_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LangTrHotfixSliceABValue other) {
      if (other == null) {
        return;
      }
      langTrHotfixSlice_.Add(other.langTrHotfixSlice_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            langTrHotfixSlice_.AddEntriesFrom(input, _repeated_langTrHotfixSlice_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            langTrHotfixSlice_.AddEntriesFrom(ref input, _repeated_langTrHotfixSlice_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LangTrHotfixConf : pb::IMessage<LangTrHotfixConf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LangTrHotfixConf> _parser = new pb::MessageParser<LangTrHotfixConf>(() => new LangTrHotfixConf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LangTrHotfixConf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.LangTrHotfixConfReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfixConf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfixConf(LangTrHotfixConf other) : this() {
      langTrHotfixSlice_ = other.langTrHotfixSlice_.Clone();
      langTrHotfixSliceAB_ = other.langTrHotfixSliceAB_.Clone();
      langTrHotfixSliceABPatch_ = other.langTrHotfixSliceABPatch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LangTrHotfixConf Clone() {
      return new LangTrHotfixConf(this);
    }

    /// <summary>Field number for the "LangTrHotfixSlice" field.</summary>
    public const int LangTrHotfixSliceFieldNumber = 1;
    private static readonly pb::FieldCodec<global::fat.rawdata.LangTrHotfix> _repeated_langTrHotfixSlice_codec
        = pb::FieldCodec.ForMessage(10, global::fat.rawdata.LangTrHotfix.Parser);
    private readonly pbc::RepeatedField<global::fat.rawdata.LangTrHotfix> langTrHotfixSlice_ = new pbc::RepeatedField<global::fat.rawdata.LangTrHotfix>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::fat.rawdata.LangTrHotfix> LangTrHotfixSlice {
      get { return langTrHotfixSlice_; }
    }

    /// <summary>Field number for the "LangTrHotfixSliceAB" field.</summary>
    public const int LangTrHotfixSliceABFieldNumber = 2;
    private static readonly pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue>.Codec _map_langTrHotfixSliceAB_codec
        = new pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.LangTrHotfixSliceABValue.Parser), 18);
    private readonly pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue> langTrHotfixSliceAB_ = new pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue> LangTrHotfixSliceAB {
      get { return langTrHotfixSliceAB_; }
    }

    /// <summary>Field number for the "LangTrHotfixSliceABPatch" field.</summary>
    public const int LangTrHotfixSliceABPatchFieldNumber = 3;
    private static readonly pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue>.Codec _map_langTrHotfixSliceABPatch_codec
        = new pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.LangTrHotfixSliceABValue.Parser), 26);
    private readonly pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue> langTrHotfixSliceABPatch_ = new pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.LangTrHotfixSliceABValue> LangTrHotfixSliceABPatch {
      get { return langTrHotfixSliceABPatch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LangTrHotfixConf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LangTrHotfixConf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!langTrHotfixSlice_.Equals(other.langTrHotfixSlice_)) return false;
      if (!LangTrHotfixSliceAB.Equals(other.LangTrHotfixSliceAB)) return false;
      if (!LangTrHotfixSliceABPatch.Equals(other.LangTrHotfixSliceABPatch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= langTrHotfixSlice_.GetHashCode();
      hash ^= LangTrHotfixSliceAB.GetHashCode();
      hash ^= LangTrHotfixSliceABPatch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      langTrHotfixSlice_.WriteTo(output, _repeated_langTrHotfixSlice_codec);
      langTrHotfixSliceAB_.WriteTo(output, _map_langTrHotfixSliceAB_codec);
      langTrHotfixSliceABPatch_.WriteTo(output, _map_langTrHotfixSliceABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      langTrHotfixSlice_.WriteTo(ref output, _repeated_langTrHotfixSlice_codec);
      langTrHotfixSliceAB_.WriteTo(ref output, _map_langTrHotfixSliceAB_codec);
      langTrHotfixSliceABPatch_.WriteTo(ref output, _map_langTrHotfixSliceABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += langTrHotfixSlice_.CalculateSize(_repeated_langTrHotfixSlice_codec);
      size += langTrHotfixSliceAB_.CalculateSize(_map_langTrHotfixSliceAB_codec);
      size += langTrHotfixSliceABPatch_.CalculateSize(_map_langTrHotfixSliceABPatch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LangTrHotfixConf other) {
      if (other == null) {
        return;
      }
      langTrHotfixSlice_.Add(other.langTrHotfixSlice_);
      langTrHotfixSliceAB_.Add(other.langTrHotfixSliceAB_);
      langTrHotfixSliceABPatch_.Add(other.langTrHotfixSliceABPatch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            langTrHotfixSlice_.AddEntriesFrom(input, _repeated_langTrHotfixSlice_codec);
            break;
          }
          case 18: {
            langTrHotfixSliceAB_.AddEntriesFrom(input, _map_langTrHotfixSliceAB_codec);
            break;
          }
          case 26: {
            langTrHotfixSliceABPatch_.AddEntriesFrom(input, _map_langTrHotfixSliceABPatch_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            langTrHotfixSlice_.AddEntriesFrom(ref input, _repeated_langTrHotfixSlice_codec);
            break;
          }
          case 18: {
            langTrHotfixSliceAB_.AddEntriesFrom(ref input, _map_langTrHotfixSliceAB_codec);
            break;
          }
          case 26: {
            langTrHotfixSliceABPatch_.AddEntriesFrom(ref input, _map_langTrHotfixSliceABPatch_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
