// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rawdata/MergeBoardGrpConf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace fat.rawdata {

  /// <summary>Holder for reflection information generated from rawdata/MergeBoardGrpConf.proto</summary>
  public static partial class MergeBoardGrpConfReflection {

    #region Descriptor
    /// <summary>File descriptor for rawdata/MergeBoardGrpConf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MergeBoardGrpConfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9yYXdkYXRhL01lcmdlQm9hcmRHcnBDb25mLnByb3RvEgdyYXdkYXRhIi0K",
            "DU1lcmdlQm9hcmRHcnASCgoCaWQYASABKAUSEAoIYm9hcmRJZHMYAiADKAUi",
            "vAEKF01lcmdlQm9hcmRHcnBNYXBBQlZhbHVlElAKEE1lcmdlQm9hcmRHcnBN",
            "YXAYASADKAsyNi5yYXdkYXRhLk1lcmdlQm9hcmRHcnBNYXBBQlZhbHVlLk1l",
            "cmdlQm9hcmRHcnBNYXBFbnRyeRpPChVNZXJnZUJvYXJkR3JwTWFwRW50cnkS",
            "CwoDa2V5GAEgASgFEiUKBXZhbHVlGAIgASgLMhYucmF3ZGF0YS5NZXJnZUJv",
            "YXJkR3JwOgI4ASKZBAoRTWVyZ2VCb2FyZEdycENvbmYSSgoQTWVyZ2VCb2Fy",
            "ZEdycE1hcBgBIAMoCzIwLnJhd2RhdGEuTWVyZ2VCb2FyZEdycENvbmYuTWVy",
            "Z2VCb2FyZEdycE1hcEVudHJ5Ek4KEk1lcmdlQm9hcmRHcnBNYXBBQhgCIAMo",
            "CzIyLnJhd2RhdGEuTWVyZ2VCb2FyZEdycENvbmYuTWVyZ2VCb2FyZEdycE1h",
            "cEFCRW50cnkSWAoXTWVyZ2VCb2FyZEdycE1hcEFCUGF0Y2gYAyADKAsyNy5y",
            "YXdkYXRhLk1lcmdlQm9hcmRHcnBDb25mLk1lcmdlQm9hcmRHcnBNYXBBQlBh",
            "dGNoRW50cnkaTwoVTWVyZ2VCb2FyZEdycE1hcEVudHJ5EgsKA2tleRgBIAEo",
            "BRIlCgV2YWx1ZRgCIAEoCzIWLnJhd2RhdGEuTWVyZ2VCb2FyZEdycDoCOAEa",
            "WwoXTWVyZ2VCb2FyZEdycE1hcEFCRW50cnkSCwoDa2V5GAEgASgJEi8KBXZh",
            "bHVlGAIgASgLMiAucmF3ZGF0YS5NZXJnZUJvYXJkR3JwTWFwQUJWYWx1ZToC",
            "OAEaYAocTWVyZ2VCb2FyZEdycE1hcEFCUGF0Y2hFbnRyeRILCgNrZXkYASAB",
            "KAkSLwoFdmFsdWUYAiABKAsyIC5yYXdkYXRhLk1lcmdlQm9hcmRHcnBNYXBB",
            "QlZhbHVlOgI4AUI9Wi1naXRsYWIuZnVucGx1cy5pby9mYXQvY29uZi9nZW4v",
            "Z29sYW5nL3Jhd2RhdGGqAgtmYXQucmF3ZGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.MergeBoardGrp), global::fat.rawdata.MergeBoardGrp.Parser, new[]{ "Id", "BoardIds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.MergeBoardGrpMapABValue), global::fat.rawdata.MergeBoardGrpMapABValue.Parser, new[]{ "MergeBoardGrpMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.MergeBoardGrpConf), global::fat.rawdata.MergeBoardGrpConf.Parser, new[]{ "MergeBoardGrpMap", "MergeBoardGrpMapAB", "MergeBoardGrpMapABPatch" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// annotation@annotation_type(type="rawdata")
  /// annotation@rawdata(row="MergeBoardGrp",table="MergeBoardGrpMap",table_wrapper="MergeBoardGrpConf",map="true",map_key_type="int32",data="MergeBoardGrpConf")
  /// annotation@ab(table_ab="MergeBoardGrpMapAB",table_ab_patch="MergeBoardGrpMapABPatch",table_ab_value="MergeBoardGrpMapABValue",ab_patch="false")
  /// annotation@filter(just_server="false",just_client="false")
  /// annotation@MergeBoardGrp(id="id")
  /// </summary>
  public sealed partial class MergeBoardGrp : pb::IMessage<MergeBoardGrp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MergeBoardGrp> _parser = new pb::MessageParser<MergeBoardGrp>(() => new MergeBoardGrp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MergeBoardGrp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.MergeBoardGrpConfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrp(MergeBoardGrp other) : this() {
      id_ = other.id_;
      boardIds_ = other.boardIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrp Clone() {
      return new MergeBoardGrp(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 唯一id从1开始
    /// annotation@field_id(id="true")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "boardIds" field.</summary>
    public const int BoardIdsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_boardIds_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> boardIds_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 同组包含的棋盘id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> BoardIds {
      get { return boardIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MergeBoardGrp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MergeBoardGrp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!boardIds_.Equals(other.boardIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= boardIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      boardIds_.WriteTo(output, _repeated_boardIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      boardIds_.WriteTo(ref output, _repeated_boardIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      size += boardIds_.CalculateSize(_repeated_boardIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MergeBoardGrp other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      boardIds_.Add(other.boardIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            boardIds_.AddEntriesFrom(input, _repeated_boardIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            boardIds_.AddEntriesFrom(ref input, _repeated_boardIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MergeBoardGrpMapABValue : pb::IMessage<MergeBoardGrpMapABValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MergeBoardGrpMapABValue> _parser = new pb::MessageParser<MergeBoardGrpMapABValue>(() => new MergeBoardGrpMapABValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MergeBoardGrpMapABValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.MergeBoardGrpConfReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrpMapABValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrpMapABValue(MergeBoardGrpMapABValue other) : this() {
      mergeBoardGrpMap_ = other.mergeBoardGrpMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrpMapABValue Clone() {
      return new MergeBoardGrpMapABValue(this);
    }

    /// <summary>Field number for the "MergeBoardGrpMap" field.</summary>
    public const int MergeBoardGrpMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.MergeBoardGrp>.Codec _map_mergeBoardGrpMap_codec
        = new pbc::MapField<int, global::fat.rawdata.MergeBoardGrp>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeBoardGrp.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.MergeBoardGrp> mergeBoardGrpMap_ = new pbc::MapField<int, global::fat.rawdata.MergeBoardGrp>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.MergeBoardGrp> MergeBoardGrpMap {
      get { return mergeBoardGrpMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MergeBoardGrpMapABValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MergeBoardGrpMapABValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!MergeBoardGrpMap.Equals(other.MergeBoardGrpMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= MergeBoardGrpMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mergeBoardGrpMap_.WriteTo(output, _map_mergeBoardGrpMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mergeBoardGrpMap_.WriteTo(ref output, _map_mergeBoardGrpMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mergeBoardGrpMap_.CalculateSize(_map_mergeBoardGrpMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MergeBoardGrpMapABValue other) {
      if (other == null) {
        return;
      }
      mergeBoardGrpMap_.Add(other.mergeBoardGrpMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mergeBoardGrpMap_.AddEntriesFrom(input, _map_mergeBoardGrpMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            mergeBoardGrpMap_.AddEntriesFrom(ref input, _map_mergeBoardGrpMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MergeBoardGrpConf : pb::IMessage<MergeBoardGrpConf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MergeBoardGrpConf> _parser = new pb::MessageParser<MergeBoardGrpConf>(() => new MergeBoardGrpConf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MergeBoardGrpConf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.MergeBoardGrpConfReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrpConf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrpConf(MergeBoardGrpConf other) : this() {
      mergeBoardGrpMap_ = other.mergeBoardGrpMap_.Clone();
      mergeBoardGrpMapAB_ = other.mergeBoardGrpMapAB_.Clone();
      mergeBoardGrpMapABPatch_ = other.mergeBoardGrpMapABPatch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeBoardGrpConf Clone() {
      return new MergeBoardGrpConf(this);
    }

    /// <summary>Field number for the "MergeBoardGrpMap" field.</summary>
    public const int MergeBoardGrpMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.MergeBoardGrp>.Codec _map_mergeBoardGrpMap_codec
        = new pbc::MapField<int, global::fat.rawdata.MergeBoardGrp>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeBoardGrp.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.MergeBoardGrp> mergeBoardGrpMap_ = new pbc::MapField<int, global::fat.rawdata.MergeBoardGrp>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.MergeBoardGrp> MergeBoardGrpMap {
      get { return mergeBoardGrpMap_; }
    }

    /// <summary>Field number for the "MergeBoardGrpMapAB" field.</summary>
    public const int MergeBoardGrpMapABFieldNumber = 2;
    private static readonly pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue>.Codec _map_mergeBoardGrpMapAB_codec
        = new pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeBoardGrpMapABValue.Parser), 18);
    private readonly pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue> mergeBoardGrpMapAB_ = new pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue> MergeBoardGrpMapAB {
      get { return mergeBoardGrpMapAB_; }
    }

    /// <summary>Field number for the "MergeBoardGrpMapABPatch" field.</summary>
    public const int MergeBoardGrpMapABPatchFieldNumber = 3;
    private static readonly pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue>.Codec _map_mergeBoardGrpMapABPatch_codec
        = new pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeBoardGrpMapABValue.Parser), 26);
    private readonly pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue> mergeBoardGrpMapABPatch_ = new pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.MergeBoardGrpMapABValue> MergeBoardGrpMapABPatch {
      get { return mergeBoardGrpMapABPatch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MergeBoardGrpConf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MergeBoardGrpConf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!MergeBoardGrpMap.Equals(other.MergeBoardGrpMap)) return false;
      if (!MergeBoardGrpMapAB.Equals(other.MergeBoardGrpMapAB)) return false;
      if (!MergeBoardGrpMapABPatch.Equals(other.MergeBoardGrpMapABPatch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= MergeBoardGrpMap.GetHashCode();
      hash ^= MergeBoardGrpMapAB.GetHashCode();
      hash ^= MergeBoardGrpMapABPatch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mergeBoardGrpMap_.WriteTo(output, _map_mergeBoardGrpMap_codec);
      mergeBoardGrpMapAB_.WriteTo(output, _map_mergeBoardGrpMapAB_codec);
      mergeBoardGrpMapABPatch_.WriteTo(output, _map_mergeBoardGrpMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mergeBoardGrpMap_.WriteTo(ref output, _map_mergeBoardGrpMap_codec);
      mergeBoardGrpMapAB_.WriteTo(ref output, _map_mergeBoardGrpMapAB_codec);
      mergeBoardGrpMapABPatch_.WriteTo(ref output, _map_mergeBoardGrpMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mergeBoardGrpMap_.CalculateSize(_map_mergeBoardGrpMap_codec);
      size += mergeBoardGrpMapAB_.CalculateSize(_map_mergeBoardGrpMapAB_codec);
      size += mergeBoardGrpMapABPatch_.CalculateSize(_map_mergeBoardGrpMapABPatch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MergeBoardGrpConf other) {
      if (other == null) {
        return;
      }
      mergeBoardGrpMap_.Add(other.mergeBoardGrpMap_);
      mergeBoardGrpMapAB_.Add(other.mergeBoardGrpMapAB_);
      mergeBoardGrpMapABPatch_.Add(other.mergeBoardGrpMapABPatch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mergeBoardGrpMap_.AddEntriesFrom(input, _map_mergeBoardGrpMap_codec);
            break;
          }
          case 18: {
            mergeBoardGrpMapAB_.AddEntriesFrom(input, _map_mergeBoardGrpMapAB_codec);
            break;
          }
          case 26: {
            mergeBoardGrpMapABPatch_.AddEntriesFrom(input, _map_mergeBoardGrpMapABPatch_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            mergeBoardGrpMap_.AddEntriesFrom(ref input, _map_mergeBoardGrpMap_codec);
            break;
          }
          case 18: {
            mergeBoardGrpMapAB_.AddEntriesFrom(ref input, _map_mergeBoardGrpMapAB_codec);
            break;
          }
          case 26: {
            mergeBoardGrpMapABPatch_.AddEntriesFrom(ref input, _map_mergeBoardGrpMapABPatch_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
