// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rawdata/MergeRuledOutputConf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace fat.rawdata {

  /// <summary>Holder for reflection information generated from rawdata/MergeRuledOutputConf.proto</summary>
  public static partial class MergeRuledOutputConfReflection {

    #region Descriptor
    /// <summary>File descriptor for rawdata/MergeRuledOutputConf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MergeRuledOutputConfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJyYXdkYXRhL01lcmdlUnVsZWRPdXRwdXRDb25mLnByb3RvEgdyYXdkYXRh",
            "Ik4KEE1lcmdlUnVsZWRPdXRwdXQSCgoCaWQYASABKAUSFAoMb3V0cHV0c0Zp",
            "eGVkGAIgAygFEhgKEG91dHB1dHNGaXhlZFRpbWUYAyADKAUizgEKGk1lcmdl",
            "UnVsZWRPdXRwdXRNYXBBQlZhbHVlElkKE01lcmdlUnVsZWRPdXRwdXRNYXAY",
            "ASADKAsyPC5yYXdkYXRhLk1lcmdlUnVsZWRPdXRwdXRNYXBBQlZhbHVlLk1l",
            "cmdlUnVsZWRPdXRwdXRNYXBFbnRyeRpVChhNZXJnZVJ1bGVkT3V0cHV0TWFw",
            "RW50cnkSCwoDa2V5GAEgASgFEigKBXZhbHVlGAIgASgLMhkucmF3ZGF0YS5N",
            "ZXJnZVJ1bGVkT3V0cHV0OgI4ASLJBAoUTWVyZ2VSdWxlZE91dHB1dENvbmYS",
            "UwoTTWVyZ2VSdWxlZE91dHB1dE1hcBgBIAMoCzI2LnJhd2RhdGEuTWVyZ2VS",
            "dWxlZE91dHB1dENvbmYuTWVyZ2VSdWxlZE91dHB1dE1hcEVudHJ5ElcKFU1l",
            "cmdlUnVsZWRPdXRwdXRNYXBBQhgCIAMoCzI4LnJhd2RhdGEuTWVyZ2VSdWxl",
            "ZE91dHB1dENvbmYuTWVyZ2VSdWxlZE91dHB1dE1hcEFCRW50cnkSYQoaTWVy",
            "Z2VSdWxlZE91dHB1dE1hcEFCUGF0Y2gYAyADKAsyPS5yYXdkYXRhLk1lcmdl",
            "UnVsZWRPdXRwdXRDb25mLk1lcmdlUnVsZWRPdXRwdXRNYXBBQlBhdGNoRW50",
            "cnkaVQoYTWVyZ2VSdWxlZE91dHB1dE1hcEVudHJ5EgsKA2tleRgBIAEoBRIo",
            "CgV2YWx1ZRgCIAEoCzIZLnJhd2RhdGEuTWVyZ2VSdWxlZE91dHB1dDoCOAEa",
            "YQoaTWVyZ2VSdWxlZE91dHB1dE1hcEFCRW50cnkSCwoDa2V5GAEgASgJEjIK",
            "BXZhbHVlGAIgASgLMiMucmF3ZGF0YS5NZXJnZVJ1bGVkT3V0cHV0TWFwQUJW",
            "YWx1ZToCOAEaZgofTWVyZ2VSdWxlZE91dHB1dE1hcEFCUGF0Y2hFbnRyeRIL",
            "CgNrZXkYASABKAkSMgoFdmFsdWUYAiABKAsyIy5yYXdkYXRhLk1lcmdlUnVs",
            "ZWRPdXRwdXRNYXBBQlZhbHVlOgI4AUI9Wi1naXRsYWIuZnVucGx1cy5pby9m",
            "YXQvY29uZi9nZW4vZ29sYW5nL3Jhd2RhdGGqAgtmYXQucmF3ZGF0YWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.MergeRuledOutput), global::fat.rawdata.MergeRuledOutput.Parser, new[]{ "Id", "OutputsFixed", "OutputsFixedTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.MergeRuledOutputMapABValue), global::fat.rawdata.MergeRuledOutputMapABValue.Parser, new[]{ "MergeRuledOutputMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.MergeRuledOutputConf), global::fat.rawdata.MergeRuledOutputConf.Parser, new[]{ "MergeRuledOutputMap", "MergeRuledOutputMapAB", "MergeRuledOutputMapABPatch" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// annotation@annotation_type(type="rawdata")
  /// annotation@rawdata(row="MergeRuledOutput",table="MergeRuledOutputMap",table_wrapper="MergeRuledOutputConf",map="true",map_key_type="int32",data="MergeRuledOutputConf")
  /// annotation@ab(table_ab="MergeRuledOutputMapAB",table_ab_patch="MergeRuledOutputMapABPatch",table_ab_value="MergeRuledOutputMapABValue",ab_patch="false")
  /// annotation@filter(just_server="false",just_client="false")
  /// annotation@MergeRuledOutput(id="id")
  /// </summary>
  public sealed partial class MergeRuledOutput : pb::IMessage<MergeRuledOutput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MergeRuledOutput> _parser = new pb::MessageParser<MergeRuledOutput>(() => new MergeRuledOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MergeRuledOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.MergeRuledOutputConfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutput(MergeRuledOutput other) : this() {
      id_ = other.id_;
      outputsFixed_ = other.outputsFixed_.Clone();
      outputsFixedTime_ = other.outputsFixedTime_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutput Clone() {
      return new MergeRuledOutput(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 合成物品id
    /// annotation@field_id(id="true")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "outputsFixed" field.</summary>
    public const int OutputsFixedFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_outputsFixed_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> outputsFixed_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 保底产出
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> OutputsFixed {
      get { return outputsFixed_; }
    }

    /// <summary>Field number for the "outputsFixedTime" field.</summary>
    public const int OutputsFixedTimeFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_outputsFixedTime_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> outputsFixedTime_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 保底次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> OutputsFixedTime {
      get { return outputsFixedTime_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MergeRuledOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MergeRuledOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!outputsFixed_.Equals(other.outputsFixed_)) return false;
      if(!outputsFixedTime_.Equals(other.outputsFixedTime_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= outputsFixed_.GetHashCode();
      hash ^= outputsFixedTime_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      outputsFixed_.WriteTo(output, _repeated_outputsFixed_codec);
      outputsFixedTime_.WriteTo(output, _repeated_outputsFixedTime_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      outputsFixed_.WriteTo(ref output, _repeated_outputsFixed_codec);
      outputsFixedTime_.WriteTo(ref output, _repeated_outputsFixedTime_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      size += outputsFixed_.CalculateSize(_repeated_outputsFixed_codec);
      size += outputsFixedTime_.CalculateSize(_repeated_outputsFixedTime_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MergeRuledOutput other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      outputsFixed_.Add(other.outputsFixed_);
      outputsFixedTime_.Add(other.outputsFixedTime_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            outputsFixed_.AddEntriesFrom(input, _repeated_outputsFixed_codec);
            break;
          }
          case 26:
          case 24: {
            outputsFixedTime_.AddEntriesFrom(input, _repeated_outputsFixedTime_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            outputsFixed_.AddEntriesFrom(ref input, _repeated_outputsFixed_codec);
            break;
          }
          case 26:
          case 24: {
            outputsFixedTime_.AddEntriesFrom(ref input, _repeated_outputsFixedTime_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MergeRuledOutputMapABValue : pb::IMessage<MergeRuledOutputMapABValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MergeRuledOutputMapABValue> _parser = new pb::MessageParser<MergeRuledOutputMapABValue>(() => new MergeRuledOutputMapABValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MergeRuledOutputMapABValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.MergeRuledOutputConfReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutputMapABValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutputMapABValue(MergeRuledOutputMapABValue other) : this() {
      mergeRuledOutputMap_ = other.mergeRuledOutputMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutputMapABValue Clone() {
      return new MergeRuledOutputMapABValue(this);
    }

    /// <summary>Field number for the "MergeRuledOutputMap" field.</summary>
    public const int MergeRuledOutputMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.MergeRuledOutput>.Codec _map_mergeRuledOutputMap_codec
        = new pbc::MapField<int, global::fat.rawdata.MergeRuledOutput>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeRuledOutput.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.MergeRuledOutput> mergeRuledOutputMap_ = new pbc::MapField<int, global::fat.rawdata.MergeRuledOutput>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.MergeRuledOutput> MergeRuledOutputMap {
      get { return mergeRuledOutputMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MergeRuledOutputMapABValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MergeRuledOutputMapABValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!MergeRuledOutputMap.Equals(other.MergeRuledOutputMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= MergeRuledOutputMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mergeRuledOutputMap_.WriteTo(output, _map_mergeRuledOutputMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mergeRuledOutputMap_.WriteTo(ref output, _map_mergeRuledOutputMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mergeRuledOutputMap_.CalculateSize(_map_mergeRuledOutputMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MergeRuledOutputMapABValue other) {
      if (other == null) {
        return;
      }
      mergeRuledOutputMap_.Add(other.mergeRuledOutputMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mergeRuledOutputMap_.AddEntriesFrom(input, _map_mergeRuledOutputMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            mergeRuledOutputMap_.AddEntriesFrom(ref input, _map_mergeRuledOutputMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MergeRuledOutputConf : pb::IMessage<MergeRuledOutputConf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MergeRuledOutputConf> _parser = new pb::MessageParser<MergeRuledOutputConf>(() => new MergeRuledOutputConf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MergeRuledOutputConf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.MergeRuledOutputConfReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutputConf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutputConf(MergeRuledOutputConf other) : this() {
      mergeRuledOutputMap_ = other.mergeRuledOutputMap_.Clone();
      mergeRuledOutputMapAB_ = other.mergeRuledOutputMapAB_.Clone();
      mergeRuledOutputMapABPatch_ = other.mergeRuledOutputMapABPatch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MergeRuledOutputConf Clone() {
      return new MergeRuledOutputConf(this);
    }

    /// <summary>Field number for the "MergeRuledOutputMap" field.</summary>
    public const int MergeRuledOutputMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.MergeRuledOutput>.Codec _map_mergeRuledOutputMap_codec
        = new pbc::MapField<int, global::fat.rawdata.MergeRuledOutput>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeRuledOutput.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.MergeRuledOutput> mergeRuledOutputMap_ = new pbc::MapField<int, global::fat.rawdata.MergeRuledOutput>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.MergeRuledOutput> MergeRuledOutputMap {
      get { return mergeRuledOutputMap_; }
    }

    /// <summary>Field number for the "MergeRuledOutputMapAB" field.</summary>
    public const int MergeRuledOutputMapABFieldNumber = 2;
    private static readonly pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue>.Codec _map_mergeRuledOutputMapAB_codec
        = new pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeRuledOutputMapABValue.Parser), 18);
    private readonly pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue> mergeRuledOutputMapAB_ = new pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue> MergeRuledOutputMapAB {
      get { return mergeRuledOutputMapAB_; }
    }

    /// <summary>Field number for the "MergeRuledOutputMapABPatch" field.</summary>
    public const int MergeRuledOutputMapABPatchFieldNumber = 3;
    private static readonly pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue>.Codec _map_mergeRuledOutputMapABPatch_codec
        = new pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.MergeRuledOutputMapABValue.Parser), 26);
    private readonly pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue> mergeRuledOutputMapABPatch_ = new pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.MergeRuledOutputMapABValue> MergeRuledOutputMapABPatch {
      get { return mergeRuledOutputMapABPatch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MergeRuledOutputConf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MergeRuledOutputConf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!MergeRuledOutputMap.Equals(other.MergeRuledOutputMap)) return false;
      if (!MergeRuledOutputMapAB.Equals(other.MergeRuledOutputMapAB)) return false;
      if (!MergeRuledOutputMapABPatch.Equals(other.MergeRuledOutputMapABPatch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= MergeRuledOutputMap.GetHashCode();
      hash ^= MergeRuledOutputMapAB.GetHashCode();
      hash ^= MergeRuledOutputMapABPatch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mergeRuledOutputMap_.WriteTo(output, _map_mergeRuledOutputMap_codec);
      mergeRuledOutputMapAB_.WriteTo(output, _map_mergeRuledOutputMapAB_codec);
      mergeRuledOutputMapABPatch_.WriteTo(output, _map_mergeRuledOutputMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mergeRuledOutputMap_.WriteTo(ref output, _map_mergeRuledOutputMap_codec);
      mergeRuledOutputMapAB_.WriteTo(ref output, _map_mergeRuledOutputMapAB_codec);
      mergeRuledOutputMapABPatch_.WriteTo(ref output, _map_mergeRuledOutputMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mergeRuledOutputMap_.CalculateSize(_map_mergeRuledOutputMap_codec);
      size += mergeRuledOutputMapAB_.CalculateSize(_map_mergeRuledOutputMapAB_codec);
      size += mergeRuledOutputMapABPatch_.CalculateSize(_map_mergeRuledOutputMapABPatch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MergeRuledOutputConf other) {
      if (other == null) {
        return;
      }
      mergeRuledOutputMap_.Add(other.mergeRuledOutputMap_);
      mergeRuledOutputMapAB_.Add(other.mergeRuledOutputMapAB_);
      mergeRuledOutputMapABPatch_.Add(other.mergeRuledOutputMapABPatch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mergeRuledOutputMap_.AddEntriesFrom(input, _map_mergeRuledOutputMap_codec);
            break;
          }
          case 18: {
            mergeRuledOutputMapAB_.AddEntriesFrom(input, _map_mergeRuledOutputMapAB_codec);
            break;
          }
          case 26: {
            mergeRuledOutputMapABPatch_.AddEntriesFrom(input, _map_mergeRuledOutputMapABPatch_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            mergeRuledOutputMap_.AddEntriesFrom(ref input, _map_mergeRuledOutputMap_codec);
            break;
          }
          case 18: {
            mergeRuledOutputMapAB_.AddEntriesFrom(ref input, _map_mergeRuledOutputMapAB_codec);
            break;
          }
          case 26: {
            mergeRuledOutputMapABPatch_.AddEntriesFrom(ref input, _map_mergeRuledOutputMapABPatch_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
