// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rawdata/SevenDayTaskDetailConf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace fat.rawdata {

  /// <summary>Holder for reflection information generated from rawdata/SevenDayTaskDetailConf.proto</summary>
  public static partial class SevenDayTaskDetailConfReflection {

    #region Descriptor
    /// <summary>File descriptor for rawdata/SevenDayTaskDetailConf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SevenDayTaskDetailConfReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRyYXdkYXRhL1NldmVuRGF5VGFza0RldGFpbENvbmYucHJvdG8SB3Jhd2Rh",
            "dGEiVAoSU2V2ZW5EYXlUYXNrRGV0YWlsEgoKAmlkGAEgASgFEgwKBGRpZmYY",
            "AiABKAUSEQoJcG9pbnRzUndkGAMgAygFEhEKCXRhc2tHcm91cBgEIAMoBSLa",
            "AQocU2V2ZW5EYXlUYXNrRGV0YWlsTWFwQUJWYWx1ZRJfChVTZXZlbkRheVRh",
            "c2tEZXRhaWxNYXAYASADKAsyQC5yYXdkYXRhLlNldmVuRGF5VGFza0RldGFp",
            "bE1hcEFCVmFsdWUuU2V2ZW5EYXlUYXNrRGV0YWlsTWFwRW50cnkaWQoaU2V2",
            "ZW5EYXlUYXNrRGV0YWlsTWFwRW50cnkSCwoDa2V5GAEgASgFEioKBXZhbHVl",
            "GAIgASgLMhsucmF3ZGF0YS5TZXZlbkRheVRhc2tEZXRhaWw6AjgBIukEChZT",
            "ZXZlbkRheVRhc2tEZXRhaWxDb25mElkKFVNldmVuRGF5VGFza0RldGFpbE1h",
            "cBgBIAMoCzI6LnJhd2RhdGEuU2V2ZW5EYXlUYXNrRGV0YWlsQ29uZi5TZXZl",
            "bkRheVRhc2tEZXRhaWxNYXBFbnRyeRJdChdTZXZlbkRheVRhc2tEZXRhaWxN",
            "YXBBQhgCIAMoCzI8LnJhd2RhdGEuU2V2ZW5EYXlUYXNrRGV0YWlsQ29uZi5T",
            "ZXZlbkRheVRhc2tEZXRhaWxNYXBBQkVudHJ5EmcKHFNldmVuRGF5VGFza0Rl",
            "dGFpbE1hcEFCUGF0Y2gYAyADKAsyQS5yYXdkYXRhLlNldmVuRGF5VGFza0Rl",
            "dGFpbENvbmYuU2V2ZW5EYXlUYXNrRGV0YWlsTWFwQUJQYXRjaEVudHJ5GlkK",
            "GlNldmVuRGF5VGFza0RldGFpbE1hcEVudHJ5EgsKA2tleRgBIAEoBRIqCgV2",
            "YWx1ZRgCIAEoCzIbLnJhd2RhdGEuU2V2ZW5EYXlUYXNrRGV0YWlsOgI4ARpl",
            "ChxTZXZlbkRheVRhc2tEZXRhaWxNYXBBQkVudHJ5EgsKA2tleRgBIAEoCRI0",
            "CgV2YWx1ZRgCIAEoCzIlLnJhd2RhdGEuU2V2ZW5EYXlUYXNrRGV0YWlsTWFw",
            "QUJWYWx1ZToCOAEaagohU2V2ZW5EYXlUYXNrRGV0YWlsTWFwQUJQYXRjaEVu",
            "dHJ5EgsKA2tleRgBIAEoCRI0CgV2YWx1ZRgCIAEoCzIlLnJhd2RhdGEuU2V2",
            "ZW5EYXlUYXNrRGV0YWlsTWFwQUJWYWx1ZToCOAFCPVotZ2l0bGFiLmZ1bnBs",
            "dXMuaW8vZmF0L2NvbmYvZ2VuL2dvbGFuZy9yYXdkYXRhqgILZmF0LnJhd2Rh",
            "dGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.SevenDayTaskDetail), global::fat.rawdata.SevenDayTaskDetail.Parser, new[]{ "Id", "Diff", "PointsRwd", "TaskGroup" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.SevenDayTaskDetailMapABValue), global::fat.rawdata.SevenDayTaskDetailMapABValue.Parser, new[]{ "SevenDayTaskDetailMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::fat.rawdata.SevenDayTaskDetailConf), global::fat.rawdata.SevenDayTaskDetailConf.Parser, new[]{ "SevenDayTaskDetailMap", "SevenDayTaskDetailMapAB", "SevenDayTaskDetailMapABPatch" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// annotation@annotation_type(type="rawdata")
  /// annotation@rawdata(row="SevenDayTaskDetail",table="SevenDayTaskDetailMap",table_wrapper="SevenDayTaskDetailConf",map="true",map_key_type="int32",data="SevenDayTaskDetailConf")
  /// annotation@ab(table_ab="SevenDayTaskDetailMapAB",table_ab_patch="SevenDayTaskDetailMapABPatch",table_ab_value="SevenDayTaskDetailMapABValue",ab_patch="false")
  /// annotation@filter(just_server="false",just_client="false")
  /// annotation@SevenDayTaskDetail(id="id")
  /// </summary>
  public sealed partial class SevenDayTaskDetail : pb::IMessage<SevenDayTaskDetail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SevenDayTaskDetail> _parser = new pb::MessageParser<SevenDayTaskDetail>(() => new SevenDayTaskDetail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SevenDayTaskDetail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.SevenDayTaskDetailConfReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetail(SevenDayTaskDetail other) : this() {
      id_ = other.id_;
      diff_ = other.diff_;
      pointsRwd_ = other.pointsRwd_.Clone();
      taskGroup_ = other.taskGroup_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetail Clone() {
      return new SevenDayTaskDetail(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 任务分组id
    /// annotation@field_id(id="true")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "diff" field.</summary>
    public const int DiffFieldNumber = 2;
    private int diff_;
    /// <summary>
    /// 活动难度
    /// 仅用做TGA
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Diff {
      get { return diff_; }
      set {
        diff_ = value;
      }
    }

    /// <summary>Field number for the "pointsRwd" field.</summary>
    public const int PointsRwdFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_pointsRwd_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> pointsRwd_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 里程碑奖励id
    /// 按序对应每一阶段里程碑奖励id
    /// （SevenDayTaskRwd.id）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> PointsRwd {
      get { return pointsRwd_; }
    }

    /// <summary>Field number for the "taskGroup" field.</summary>
    public const int TaskGroupFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_taskGroup_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> taskGroup_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 任务组数据
    /// 按序对应每一阶段的任务组id
    /// （SevenDayTaskGroup.id）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> TaskGroup {
      get { return taskGroup_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SevenDayTaskDetail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SevenDayTaskDetail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Diff != other.Diff) return false;
      if(!pointsRwd_.Equals(other.pointsRwd_)) return false;
      if(!taskGroup_.Equals(other.taskGroup_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Diff != 0) hash ^= Diff.GetHashCode();
      hash ^= pointsRwd_.GetHashCode();
      hash ^= taskGroup_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Diff != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Diff);
      }
      pointsRwd_.WriteTo(output, _repeated_pointsRwd_codec);
      taskGroup_.WriteTo(output, _repeated_taskGroup_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Diff != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Diff);
      }
      pointsRwd_.WriteTo(ref output, _repeated_pointsRwd_codec);
      taskGroup_.WriteTo(ref output, _repeated_taskGroup_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Diff != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diff);
      }
      size += pointsRwd_.CalculateSize(_repeated_pointsRwd_codec);
      size += taskGroup_.CalculateSize(_repeated_taskGroup_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SevenDayTaskDetail other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Diff != 0) {
        Diff = other.Diff;
      }
      pointsRwd_.Add(other.pointsRwd_);
      taskGroup_.Add(other.taskGroup_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Diff = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            pointsRwd_.AddEntriesFrom(input, _repeated_pointsRwd_codec);
            break;
          }
          case 34:
          case 32: {
            taskGroup_.AddEntriesFrom(input, _repeated_taskGroup_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Diff = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            pointsRwd_.AddEntriesFrom(ref input, _repeated_pointsRwd_codec);
            break;
          }
          case 34:
          case 32: {
            taskGroup_.AddEntriesFrom(ref input, _repeated_taskGroup_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SevenDayTaskDetailMapABValue : pb::IMessage<SevenDayTaskDetailMapABValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SevenDayTaskDetailMapABValue> _parser = new pb::MessageParser<SevenDayTaskDetailMapABValue>(() => new SevenDayTaskDetailMapABValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SevenDayTaskDetailMapABValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.SevenDayTaskDetailConfReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetailMapABValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetailMapABValue(SevenDayTaskDetailMapABValue other) : this() {
      sevenDayTaskDetailMap_ = other.sevenDayTaskDetailMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetailMapABValue Clone() {
      return new SevenDayTaskDetailMapABValue(this);
    }

    /// <summary>Field number for the "SevenDayTaskDetailMap" field.</summary>
    public const int SevenDayTaskDetailMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail>.Codec _map_sevenDayTaskDetailMap_codec
        = new pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.SevenDayTaskDetail.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail> sevenDayTaskDetailMap_ = new pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail> SevenDayTaskDetailMap {
      get { return sevenDayTaskDetailMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SevenDayTaskDetailMapABValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SevenDayTaskDetailMapABValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!SevenDayTaskDetailMap.Equals(other.SevenDayTaskDetailMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= SevenDayTaskDetailMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      sevenDayTaskDetailMap_.WriteTo(output, _map_sevenDayTaskDetailMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      sevenDayTaskDetailMap_.WriteTo(ref output, _map_sevenDayTaskDetailMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += sevenDayTaskDetailMap_.CalculateSize(_map_sevenDayTaskDetailMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SevenDayTaskDetailMapABValue other) {
      if (other == null) {
        return;
      }
      sevenDayTaskDetailMap_.Add(other.sevenDayTaskDetailMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sevenDayTaskDetailMap_.AddEntriesFrom(input, _map_sevenDayTaskDetailMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            sevenDayTaskDetailMap_.AddEntriesFrom(ref input, _map_sevenDayTaskDetailMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SevenDayTaskDetailConf : pb::IMessage<SevenDayTaskDetailConf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SevenDayTaskDetailConf> _parser = new pb::MessageParser<SevenDayTaskDetailConf>(() => new SevenDayTaskDetailConf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SevenDayTaskDetailConf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::fat.rawdata.SevenDayTaskDetailConfReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetailConf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetailConf(SevenDayTaskDetailConf other) : this() {
      sevenDayTaskDetailMap_ = other.sevenDayTaskDetailMap_.Clone();
      sevenDayTaskDetailMapAB_ = other.sevenDayTaskDetailMapAB_.Clone();
      sevenDayTaskDetailMapABPatch_ = other.sevenDayTaskDetailMapABPatch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayTaskDetailConf Clone() {
      return new SevenDayTaskDetailConf(this);
    }

    /// <summary>Field number for the "SevenDayTaskDetailMap" field.</summary>
    public const int SevenDayTaskDetailMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail>.Codec _map_sevenDayTaskDetailMap_codec
        = new pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::fat.rawdata.SevenDayTaskDetail.Parser), 10);
    private readonly pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail> sevenDayTaskDetailMap_ = new pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::fat.rawdata.SevenDayTaskDetail> SevenDayTaskDetailMap {
      get { return sevenDayTaskDetailMap_; }
    }

    /// <summary>Field number for the "SevenDayTaskDetailMapAB" field.</summary>
    public const int SevenDayTaskDetailMapABFieldNumber = 2;
    private static readonly pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue>.Codec _map_sevenDayTaskDetailMapAB_codec
        = new pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.SevenDayTaskDetailMapABValue.Parser), 18);
    private readonly pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue> sevenDayTaskDetailMapAB_ = new pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue> SevenDayTaskDetailMapAB {
      get { return sevenDayTaskDetailMapAB_; }
    }

    /// <summary>Field number for the "SevenDayTaskDetailMapABPatch" field.</summary>
    public const int SevenDayTaskDetailMapABPatchFieldNumber = 3;
    private static readonly pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue>.Codec _map_sevenDayTaskDetailMapABPatch_codec
        = new pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::fat.rawdata.SevenDayTaskDetailMapABValue.Parser), 26);
    private readonly pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue> sevenDayTaskDetailMapABPatch_ = new pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::fat.rawdata.SevenDayTaskDetailMapABValue> SevenDayTaskDetailMapABPatch {
      get { return sevenDayTaskDetailMapABPatch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SevenDayTaskDetailConf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SevenDayTaskDetailConf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!SevenDayTaskDetailMap.Equals(other.SevenDayTaskDetailMap)) return false;
      if (!SevenDayTaskDetailMapAB.Equals(other.SevenDayTaskDetailMapAB)) return false;
      if (!SevenDayTaskDetailMapABPatch.Equals(other.SevenDayTaskDetailMapABPatch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= SevenDayTaskDetailMap.GetHashCode();
      hash ^= SevenDayTaskDetailMapAB.GetHashCode();
      hash ^= SevenDayTaskDetailMapABPatch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      sevenDayTaskDetailMap_.WriteTo(output, _map_sevenDayTaskDetailMap_codec);
      sevenDayTaskDetailMapAB_.WriteTo(output, _map_sevenDayTaskDetailMapAB_codec);
      sevenDayTaskDetailMapABPatch_.WriteTo(output, _map_sevenDayTaskDetailMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      sevenDayTaskDetailMap_.WriteTo(ref output, _map_sevenDayTaskDetailMap_codec);
      sevenDayTaskDetailMapAB_.WriteTo(ref output, _map_sevenDayTaskDetailMapAB_codec);
      sevenDayTaskDetailMapABPatch_.WriteTo(ref output, _map_sevenDayTaskDetailMapABPatch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += sevenDayTaskDetailMap_.CalculateSize(_map_sevenDayTaskDetailMap_codec);
      size += sevenDayTaskDetailMapAB_.CalculateSize(_map_sevenDayTaskDetailMapAB_codec);
      size += sevenDayTaskDetailMapABPatch_.CalculateSize(_map_sevenDayTaskDetailMapABPatch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SevenDayTaskDetailConf other) {
      if (other == null) {
        return;
      }
      sevenDayTaskDetailMap_.Add(other.sevenDayTaskDetailMap_);
      sevenDayTaskDetailMapAB_.Add(other.sevenDayTaskDetailMapAB_);
      sevenDayTaskDetailMapABPatch_.Add(other.sevenDayTaskDetailMapABPatch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sevenDayTaskDetailMap_.AddEntriesFrom(input, _map_sevenDayTaskDetailMap_codec);
            break;
          }
          case 18: {
            sevenDayTaskDetailMapAB_.AddEntriesFrom(input, _map_sevenDayTaskDetailMapAB_codec);
            break;
          }
          case 26: {
            sevenDayTaskDetailMapABPatch_.AddEntriesFrom(input, _map_sevenDayTaskDetailMapABPatch_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            sevenDayTaskDetailMap_.AddEntriesFrom(ref input, _map_sevenDayTaskDetailMap_codec);
            break;
          }
          case 18: {
            sevenDayTaskDetailMapAB_.AddEntriesFrom(ref input, _map_sevenDayTaskDetailMapAB_codec);
            break;
          }
          case 26: {
            sevenDayTaskDetailMapABPatch_.AddEntriesFrom(ref input, _map_sevenDayTaskDetailMapABPatch_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
